# fly.toml app configuration file generated for fast-zero-twilight-fire-9980 on 2024-08-02T17:20:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-zero-twilight-fire-9980'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
